const express = require('express')
const bodyParser = require('body-parser')
const app = express()
const path = require('path')
const rootDir = require('./util/path')
const adminRouter = require('./Routes/admin')
app.set('view engine', 'ejs')
app.set('views', 'views')
app.use(require('./controller/controller').updateProductMiddleware)
app.use(express.static(path.join(rootDir.path, 'public')))
app.use(bodyParser.urlencoded({ extended: true }))
app.use('/admin',adminRouter)
app.use(require('./Routes/shop').Router)

app.listen(3000)